# ==========================================
# Configuración de Base de Datos (Aiven MySQL)
# ==========================================
spring.datasource.url=jdbc:mysql://mysql-1b522c95-gabrielmolina8021-5ea2.a.aivencloud.com:26251/defaultdb?useSSL=true&requireSSL=true&verifyServerCertificate=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2,TLSv1.3&serverTimezone=CET

spring.datasource.username=avnadmin
spring.datasource.password=AVNS_k0HuJxUPVBfdsK5Vu39
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# Configuración de JPA / Hibernate
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.database=MYSQL
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug

spring.jpa.hibernate.ddl-auto=update

# ==========================================
# Configuración de Archivos y Puerto
# ==========================================
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB
spring.servlet.multipart.enabled=true

server.port=8090
