spring.datasource.url=jdbc:mysql://mysql-1b522c95-gabrielmolina8021-5ea2.a.aivencloud.com:26251/defaultdb?ssl-mode=REQUIRED&serverTimezone=CET
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_k0HuJxUPVBfdsK5Vu39
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.database=MYSQL
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB
spring.servlet.multipart.enabled=true

server.port=8090
